
#undef  CONFIG_OV7670_SUPPORT
#undef  CONFIG_OV7725_SUPPORT
#undef  CONFIG_NT99141_SUPPORT
//#undef  CONFIG_OV2640_SUPPORT
//#undef  CONFIG_OV3660_SUPPORT
#undef  CONFIG_OV5640_SUPPORT
#undef  CONFIG_GC2145_SUPPORT
#undef  CONFIG_GC032A_SUPPORT
//#undef  CONFIG_GC0308_SUPPORT
#undef  CONFIG_BF3005_SUPPORT
#undef  CONFIG_BF20A6_SUPPORT
#undef  CONFIG_SC030IOT_SUPPORT
//#undef  CONFIG_SCCB_HARDWARE_I2C_PORT1
//#undef  CONFIG_SCCB_CLK_FREQ
//#define CONFIG_SCCB_CLK_FREQ 100000
#undef  CONFIG_GC_SENSOR_SUBSAMPLE_MODE
//#undef  CONFIG_CAMERA_CORE0
#define CONFIG_CAMERA_DMA_BUFFER_SIZE_MAX 32768

#undef  CONFIG_SC101IOT_SUPPORT
#undef  CONFIG_SC101IOT_720P_15FPS_ENABLED
#undef  CONFIG_CAMERA_CONVERTER_ENABLED

